### ISSUE TITLE
Better support for mutually recursive types

### ISSUE THREAD

**Issue by ejgallego** [janestreet/ppx_python#1]
Dear ppx_python devs,

thanks for the tool, I managed to serialize a quite large codebase, however my main roadblock is lack of support for mutually recursive types:

```ocaml
  type t =
    | Base of int
    | App of t * u
  and u =
    | Lam of t
  [@@deriving python]
```
will fail with `Only variables are allowed as left-hand side of `let rec'` . Likely this is easy to fix as `ppx_sexp_conv` does support this without problems. I'd be happy to try myself if you give me some hints.

Thanks a lot!

**Comment by LaurentMazare** [comment]
Thanks for the feedback, we'll have a look at how hard this is to add.
In the meantime could I suggest the following hack if you have the possibility to modify the types in your codebase?

```ocaml
type 'a t_ =
  | Base of int
  | App of 'a t_ * 'a
[@@deriving python]

type u = Lam of u t_ [@@deriving python]

type t = u t_ [@@deriving python]
```

**Comment by ejgallego** [comment]
Thanks @LaurentMazare , it is good to know the workaround, unfortunately in our case it'd be too costly to do in general, but indeed we can add a few wrappers to get around this for now.

**Comment by LaurentMazare** [comment]
@ejgallego a new version has just been released and it should support mutually recursive types.
You can see the example you gave in our [test suite](https://github.com/janestreet/ppx_python/blob/d30dc29406f35ffc89689ca7f379cbb249afd1fb/test/ppx_test.ml#L379-L405).
Thanks for the suggestion and let us know if you find any other issues/missing bits.

**Comment by ejgallego** [comment]
Great, thanks a lot for super quick response! I will update pycoq and report back.

**Comment by LaurentMazare** [comment]
Sure, I'm closing this issue for now, don't hesitate to reopen it or open a new one if any issue.

**Comment by nilsbecker** [comment]
I stumbled on a related problem which might either a bug or I'm just doing it wrong:
```ocaml
module M = struct type t = Node of int * t * t  | Leaf end
type tt = M.t [@@deriving python]
```
This fails with `Error: Unbound value M.python_of_t`. I.e. the ppx looks for a deriver for `t` on the rhs of the type definition in the outer scope not inside the module `M`. Is this something that could be done or is it impossible in principle? I was trying to retrofit python converters for types defined in other modules.

**Comment by nilsbecker** [comment]
As a workaround I tried to define a new module and include the imported one.
```
module MM = struct include M type tt = M.t [@@deriving python] end
```
but that failed as well

**Comment by nilsbecker** [comment]
ok, i got one thing working, by replicating `ppx_deriving`'s examples.
```ocaml
module MM = type tt = M.t = Node of int * tt * tt | Leaf [@@deriving python] end
```
which requires repeating the type definition but seems to work in `MM.python_of_tt NN.t`
