### ISSUE TITLE
Polymorphic Variants

### ISSUE THREAD

**Issue by nilsbecker** [janestreet/ppx_python#4]
I was unable to get ``type tree = [`Node of int * tree list] [@@deriving python]`` to work. It seems that polymorphic variants are not supported. Would it be possible to add these?

**Comment by LaurentMazare** [comment]
Apologies for the delay, the latest commit should add some basic support for polymorphic variants and your example should now work fine. Let us know if you run into any further issue with this.

**Comment by LaurentMazare** [comment]
Closing this for now as this should be fixed, feel free to re-open should you run into any issues.
